#! /usr/bin/env bash
# This script is used to bring the working directory into a shape where it can be released as a tar Archive.

make doc

find . -name ".gitignore" -or -name ".cdtproject" -or -name ".project" | while IFS= read i; do
	rm -f "$i"
done

rm -f "do-{release,tag}"
